name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: 
    runs-on: 
    container:
      image: 

    steps:
      - name: test
      - run: wget https://raw.githubusercontent.com/philip330/max/main/scala.tar.gz
